### ISSUE TITLE
Permission denied 运行就报错了

### ISSUE THREAD

**Issue by sunzcdev** [DoctorQ/minicap_java#1]
com.android.ddmlib.SyncException: Permission denied
03:32:41 E/ddms: transfer error: Permission denied
03:32:41 E/Device: Error during Sync: Permission denied
    at com.android.ddmlib.SyncService.doPushFile(SyncService.java:698)
    at com.android.ddmlib.SyncService.pushFile(SyncService.java:380)
    at com.android.ddmlib.Device.pushFile(Device.java:778)
    at com.wuba.minicap.MiniCapUtil.init(MiniCapUtil.java:95)
    at com.wuba.minicap.MiniCapUtil.<init>(MiniCapUtil.java:70)
    at com.wuba.gui.MinicapTest$MyPanel.<init>(MinicapTest.java:77)

**Comment by 756718646** [comment]
我也有同样的问题
12:21:40 E/ddms: transfer error: Permission denied
12:21:40 E/Device: Error during Sync: Permission denied
com.android.ddmlib.SyncException: Permission denied
    at com.android.ddmlib.SyncService.doPushFile(SyncService.java:703)
    at com.android.ddmlib.SyncService.pushFile(SyncService.java:380)
    at com.android.ddmlib.Device.pushFile(Device.java:632)
    at com.wuba.minicap.MiniCapUtil.init(MiniCapUtil.java:95)
    at com.wuba.minicap.MiniCapUtil.<init>(MiniCapUtil.java:70)
    at com.wuba.gui.MinicapTest$MyPanel.<init>(MinicapTest.java:77)
    at com.wuba.gui.MinicapTest.<init>(MinicapTest.java:50)
    at com.wuba.gui.MinicapTest.main(MinicapTest.java:68)

**Comment by sunzcdev** [comment]
解决方法很简单，在pull文件的时候，remote地址中的路径分隔符错了，不应该使用File.sperator直接使用/就可以了

2016年8月5日 00:22，"yongzheng" <notifications@github.com<mailto:notifications@github.com>>写道：

我也有同样的问题
12:21:40 E/ddms: transfer error: Permission denied
12:21:40 E/Device: Error during Sync: Permission denied
com.android.ddmlib.SyncException: Permission denied
at com.android.ddmlib.SyncService.doPushFile(SyncService.java:703)
at com.android.ddmlib.SyncService.pushFile(SyncService.java:380)
at com.android.ddmlib.Device.pushFile(Device.java:632)
at com.wuba.minicap.MiniCapUtil.init(MiniCapUtil.java:95)
at com.wuba.minicap.MiniCapUtil.(MiniCapUtil.java:70)
at com.wuba.gui.MinicapTest$MyPanel.(MinicapTest.java:77)
at com.wuba.gui.MinicapTest.(MinicapTest.java:50)
at com.wuba.gui.MinicapTest.main(MinicapTest.java:68)

**Comment by shatian114** [comment]
这提示明显就是没有运行权限，sudo chmod +x run.sh

**Comment by 756718646** [comment]
@shatian114 不对，其实引起“运行权限”是因为File.sperator，我在window编译运行时候，File.sperator这个路径目录是window平台的，但是这个目录其实是linux的minicap的路径，是不同系统的目录分隔符问题

**Comment by shatian114** [comment]
@756718646 懂了
